name: Build DerivProSuite APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm install --force
          npm install -g eas-cli

      - name: 🔑 Setup Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: 🚀 Build APK
        run: |
          npx eas-cli build --platform android \
            --profile preview \
            --non-interactive \
            --no-wait
